name: one-kvm-full-arm
services:
  one-kvm-full:
    container_name: one-kvm
    hostname: one-kvm
    image: registry.cn-hangzhou.aliyuncs.com/silentwind/one-kvm-full:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    cpu_shares: 90
    command: []
    environment: {}
    volumes:
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /sys
        target: /sys
        read_only: true
    deploy:
      resources:
        limits:
          memory: 981M
    labels:
      org.opencontainers.image.icon: https://cdn.jsdelivr.net/gh/wangweiwei104/CasaOS-AppStore-Play@main/Apps_arm/OneKVM/icon.png
    stdin_open: true
    tty: true
    x-casaos:
      envs: []
      ports: []
      volumes:
        - container: /dev
          description:
            en_us: Access to hardware devices (USB/Video)
            zh_cn: 访问硬件设备（USB/视频采集）
        - container: /sys
          description:
            en_us: System information access
            zh_cn: 系统信息访问

x-casaos:
  architectures:
    - arm
  main: one-kvm-full
  author: WW
  category: KVM
  description:
    en_us: An open and lightweight IP-KVM solution written in Rust, enabling BIOS-level remote management. Requires compatible HDMI capture device and USB OTG support.
    zh_cn: Rust 编写的开放轻量 IP-KVM 解决方案，实现 BIOS 级远程管理。需要兼容的 HDMI 采集卡和 USB OTG 支持。
  developer: silentwind
  icon: https://cdn.jsdelivr.net/gh/wangweiwei104/CasaOS-AppStore-Play@main/Apps_arm/OneKVM/icon.png
  screenshot_link: []
  tagline:
    en_us: An open and lightweight IP-KVM
    zh_cn: 轻量 IP-KVM 解决方案
  thumbnail: https://cdn.jsdelivr.net/gh/wangweiwei104/CasaOS-AppStore-Play@main/Apps_arm/OneKVM/icon.png
  tips:
    en_us: Access via port 8080. Ensure your user has permission to access /dev/video* and /dev/hidg*. Running in Host mode.
    zh_cn: 请访问 8080 端口。请确保当前用户有权限访问 /dev/video* 和 /dev/hidg* 设备。应用运行于 Host 网络模式。
  title:
    en_us: One-KVM
    zh_cn: One-KVM 远程控制
  index: /
  hostname: ""
  port_map: "8080"
  is_uncontrolled: false
