name: gostc-arm
services:
  gostc-arm:
    container_name: gostc-arm
    hostname: gostc-arm
    image: sianhh/gostc:latest
    restart: unless-stopped
    network_mode: host
    privileged: false
    cpu_shares: 90
    command:
      - --tls=true
      - -addr
      - gost.sian.one
      - -key
      - xxxxxx-xxxx-xxxxxx-xxxxxx
    deploy:
      resources:
        limits:
          memory: 256M
    labels:
      org.opencontainers.image.icon: https://cdn.jsdelivr.net/gh/wangweiwei104/CasaOS-AppStore-Play@main/Apps_arm/gostc/icon.png
x-casaos:
  architectures:
    - arm
  main: gostc-arm
  author: WW
  category: Network
  description:
    en_us: GOSTC is a simple wrapper client for the GOST tunnel.
    zh_cn: GOSTC 是一个简单的 GOST 隧道客户端。
  developer: sianhh
  icon: https://cdn.jsdelivr.net/gh/wangweiwei104/CasaOS-AppStore-Play@main/Apps_arm/gostc/icon.png
  screenshot_link: []
  tagline:
    en_us: GOST tunnel client
    zh_cn: GOST 隧道客户端
  thumbnail: https://cdn.jsdelivr.net/gh/wangweiwei104/CasaOS-AppStore-Play@main/Apps_arm/gostc/icon.png
  tips:
    en_us: Please modify the command parameters to set your own server address and key.
    zh_cn: 请修改命令参数（command）以设置你自己的服务器地址和密钥。
  title:
    en_us: GOSTC
    zh_cn: GOSTC
  index: /
  hostname: gost.sian.one/dashboard
  scheme: https
  is_uncontrolled: false
  port_map: ""
