name: smartstrm
services:
  smartstrm:
    image: cp0204/smartstrm:latest
    container_name: smartstrm
    restart: unless-stopped
    network_mode: host
    volumes:
      - /DATA/AppData/smartstrm/config:/app/config # 挂载配置目录
      - /DATA/AppData/smartstrm/logs:/app/logs # 挂载日志目录，可选
      - /DATA/AppData/smartstrm/strm:/strm # 挂载 STRM 生成目录
    environment:
      - PORT=8024 # 管理端口，可选
      - ADMIN_USERNAME=admin # 管理用户名
      - ADMIN_PASSWORD=admin123 # 管理用户密码
      - LICENSE= # 许可证字符串（如有）
    deploy:
      resources:
        reservations:
          memory: 128M

x-casaos:
  architectures:
    - amd64
    - arm64
  main: smartstrm
  store_app_id: smartstrm
  author: Cp0204
  category: Media
  description:
    en_us: A media library STRM file generation tool. It works elegantly with Emby, supports 302 direct link playback, and supports synchronous deletion of remote files.
    zh_cn: 一个媒体库 STRM 文件生成工具。和 Emby 优雅配合，支持 302 直链播放，支持同步删除远端文件。正如其名，配合 quark-auto-save/CloudSaver, OpenList, Emby 力求即存即看。🥳
  developer: Cp0204
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/smartstrm/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/smartstrm/screenshot-1.png
  tagline:
    en_us: A media library STRM file generation tool
    zh_cn: 媒体库 STRM 文件生成工具
  tips:
    before_install:
      en_us: Default username `admin` , password `admin123`
      zh_cn: 默认用户名 `admin`，密码 `admin123`
  title:
    en_us: SmartStrm
  index: /
  port_map: "8024"
